### ISSUE TITLE
Conflict when using google maps sdk plugin

### ISSUE THREAD

**Issue by yencolon** [tylergrinn/nativescript-plugin-google-places#5]
Hi, recently i tried to use this plugin  in one of my projects, but when i installed and try to build,  a merge conflit error with the com.google.android.geo.API_KEY, I'm also using google maps sdk plugin.. any advise? 

> Manifest merger failed : Attribute meta-data#com.google.android.geo.API_KEY@value value=(@string/nativescript_google_maps_api_key) from AndroidManifest.xml:9:13-69
  is also present at AndroidManifest.xml:9:13-30 value={api key}.
      Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:7:9-9:72 to override.

I tried to use the tools:replace, but i guess i'm using it in the wrong way

**Comment by dilarion** [comment]
Hi,
This is because the api_key conflicted with google maps sdk plugin. My solution is remove one of the api key (google maps sdk plugin api key). Edit the plugin's Android Manifest (not application Manifest) at directory `node_modules/nativescript-google-maps-sdk/platforms/android/AndroidManifest.xml`

remove `<meta-data .... />` tag inside the `<application></application>`
and then rebuild the app.
