### ISSUE TITLE
Could not find com.google.android.gms:play-services:15.0.1

### ISSUE THREAD

**Issue by standevo** [tylergrinn/nativescript-plugin-google-places#6]
I use also nativescript google maps sdk with specified play-service version of 15.0.1 without any problem, but then i try to install this plugin i get the error:

`Could not find com.google.android.gms:play-services:15.0.1.`

Thank you.

**Comment by burkongla** [comment]
In case you still have the issue, and for others who might experience this same issue. This is what worked for me:

1. Go to the include.gradle file in node_modules/nativescript-plugin-google-places/platforms/android. Change `compile "com.google.android.gms:play-services:$googlePlayServicesVersion" `

to

`compile "com.google.android.gms:play-services-places:$googlePlayServicesVersion"` notice how you need to compile the specific part of google play-services that you need, in this case play-services-places instead of just play-services. Might also work with base or something, but I never tried it.

2. You will get an error about the LatLong function, it should be LatLng. You can just use the PR from debevv https://github.com/tylergrinn/nativescript-plugin-google-places/pull/3/files which has the changes needed.

**Comment by hariaravind10** [comment]
> 1. node_modules/nativescript-plugin-google-places/platforms/android
changing to this 
`compile "com.google.android.gms:play-services-places:$googlePlayServicesVersion"`
worked .. Thanks alot 👍 
![screen shot 2018-10-29 at 11 25 24 am 2](https://user-images.githubusercontent.com/34663118/47631805-8be8ad00-db6d-11e8-8b8c-04641a36844b.png)
